inherit_from: configs/StereoMIS/stereomis.yaml
timesteps:  4000
mapping:
  bound: [[-1.8,2.1],[-2,1.2],[-0.1,2.7]]
  marching_cubes_bound: [[-1.8,2.1],[-2,1.2],[-0.1,2.7]]
  #bound: [[-3.0,3.0],[-3.0,3.0],[2.0,4]]
  #marching_cubes_bound: [[-3.0,3.0],[-3.0,3.0],[2.0,4]]

data:
  datadir: data/P2_1
  trainskip: 1
  output: output/StereoMIS/P2_1
  exp_name: demo
