inherit_from: configs/Super/Super.yaml
timesteps:  151
mapping:
  bound: [[-0.5,0.5],[-0.4,0.4],[-0.01,1.2]]
  marching_cubes_bound: [[-0.5,0.5],[-0.4,0.4],[-0.01,1.2]]
  #bound: [[-3.0,3.0],[-3.0,3.0],[2.0,4]]
  #marching_cubes_bound: [[-3.0,3.0],[-3.0,3.0],[2.0,4]]

data:
  datadir: data/trail4
  trainskip: 1
  output: output/trail4
  exp_name: demo
